name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: vatsal-sharma2003
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake.gif

      - name: Push the generated snake animation
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated snake animation"
          add: "output/"
