name: Generate Snake GIF for README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Snake GIF
      uses: Platane/snk@v2
      with:
        github_user: 'Vatsal-Sharma2003' # your GitHub username
        svg_out_path: './github-contribution-grid-snake.svg'

    - name: Commit snake gif
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'github-actions[bot]'
        author_email: '41898282+github-actions[bot]@users.noreply.github.com'
        message: 'Update snake gif for README'
        add: './github-contribution-grid-snake.svg'
